components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Product:
      properties:
        adiitional_params:
          title: Adiitional Params
          type: string
        bank_name:
          title: Bank Name
          type: string
        credit_name:
          title: Credit Name
          type: string
        id:
          title: Id
          type: integer
        max_months:
          title: Max Months
          type: integer
        max_precent:
          title: Max Precent
          type: number
        max_sum:
          title: Max Sum
          type: number
        min_percent:
          title: Min Percent
          type: number
        min_scoring:
          default: 0
          title: Min Scoring
          type: integer
        type:
          title: Type
          type: string
      required:
      - bank_name
      - min_percent
      - max_precent
      - max_sum
      - type
      title: Product
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/products:
    get:
      operationId: get_products_api_products_get
      parameters:
      - in: query
        name: type
        required: false
        schema:
          title: Type
          type: string
      - in: query
        name: min_percent
        required: false
        schema:
          title: Min Percent
          type: number
      - in: query
        name: max_percent
        required: false
        schema:
          title: Max Percent
          type: number
      - in: query
        name: scoring
        required: false
        schema:
          title: Scoring
          type: integer
      - in: query
        name: max_sum
        required: false
        schema:
          title: Max Sum
          type: number
      - in: query
        name: max_months
        required: false
        schema:
          title: Max Months
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                title: Response Get Products Api Products Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Products
  /openapi.yaml:
    get:
      operationId: get_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Retrieve OpenAPI schema in YAML format
      tags:
      - docs
